
title: Nitin Surya
url: "https://nitinsurya.github.io"
baseurl: "https://nitinsurya.github.io/" #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-2
#style: styles-3
#style: styles-4
style: styles-5
#style: styles-6


#Profile information
name: Nitin Surya
tagline: Part time coder and full-time foodie. AI and ML devotee.
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: nitinsurya1991@gmail.com
phone: 3128749015
linkedin: nitinsurya
github: nitinsurya
twitter: nitinsurya

#Update all the sections by editing the files inside _includes folder.
